language: go

go:
  - 1.9

before_install:
  - go get
  - pip install --user codecov

script:
  - go build
  - ./geotiff tags testdata/ch_zh_topo_lzw.tiff
  - go test -coverprofile=cov-tags -covermode=atomic github.com/teris-io/geotiff/tags

after_success:
  - echo cov-tags > coverage.txt
  - codecov
